### ISSUE TITLE
Announcements on discourse?

### ISSUE THREAD

**Issue by paluh** [athanclark/purescript-tuples-native#1]
Hi @athanclark,

Sorry for spamming you here as this is rather wider question.

Would you mind to post some announcements on discourse.purescript.org, so the whole ecosystem can know about your cool and useful libraries (and maybe we can help to write some docs :-P). If you don't want to spend time on this but you think it is good idea please let me know so maybe I can write some small infos on every release ;-)

Thanks!

**Comment by athanclark** [comment]
Hey thank you @paluh, I plan on writing extensive documentation, with a whole taxonomy of the different libs I've authored and how they work, but I'm actually going through _all_ of my github repos just to re-upload better inline docs :| sorry about that!!

**Comment by athanclark** [comment]
Just wrote one :) I'm gonna populate it with a few. Thank you for letting me know about this!
